apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subjectpermissions.managed.openshift.io
spec:
  group: managed.openshift.io
  names:
    kind: SubjectPermission
    listKind: SubjectPermissionList
    plural: subjectpermissions
    singular: subjectpermission
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterPermissions:
              description: List of permissions applied at Cluster scope
              items:
                type: string
              type: array
            permissions:
              description: List of permissions applied at Namespace scope
              items:
                properties:
                  allowFirst:
                    description: Flag to indicate if "allow" regex is applied first
                      If 'true' order is Allow then Deny, Else order is Deny then
                      Allow
                    type: boolean
                  clusterRoleName:
                    description: ClusterRoleName to bind to the Subject as a RoleBindings
                      in allowed Namespaces
                    type: string
                  namespacesAllowedRegex:
                    description: NamespacesAllowedRegex representing allowed Namespaces
                    type: string
                  namespacesDeniedRegex:
                    description: NamespacesDeniedRegex representing denied Namespaces
                    type: string
                required:
                - clusterRoleName
                - allowFirst
                type: object
              type: array
            subjectKind:
              description: Kind of the Subject that is being granted permissions by
                the operator
              type: string
            subjectName:
              description: Name of the Subject granted permissions by the operator
              type: string
          required:
          - subjectKind
          - subjectName
          type: object
        status:
          properties:
            conditions:
              description: List of conditions for the CR
              items:
                properties:
                  clusterRoleName:
                    description: ClusterRoleName in which this condition is true
                    items:
                      type: string
                    type: array
                  lastTransitionTime:
                    description: LastTransitionTime is the last time this condition
                      was active for the CR
                    format: date-time
                    type: string
                  message:
                    description: Message related to the condition
                    type: string
                  state:
                    description: State that this condition represents
                    type: string
                  status:
                    description: Flag to indicate if condition status is currently
                      active
                    type: boolean
                required:
                - lastTransitionTime
                - clusterRoleName
                - status
                - state
                type: object
              type: array
            state:
              description: State that this condition represents
              type: string
          required:
          - state
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
