kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-permissions-operator
subjects:
- kind: ServiceAccount
  name: rbac-permissions-operator
  namespace: openshift-rbac-permissions
roleRef:
  kind: ClusterRole
  name: rbac-permissions-operator
  apiGroup: rbac.authorization.k8s.io