apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: rbac-permissions-operator-0.0.1
  namespace: placeholder
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: Operator to Manage Rbac Permissions for OpenShift Clusters.
    containerImage: quay.io/app-sre/rbac-permissions-operator:latest
    createdAt: "2019-04-10T17:34:33Z"
    support: Sam Nguyen
spec:
  displayName: rbac-permissions-operator
  description: Operator to Manage Rbac Permissions for OpenShift Clusters.
  keywords:
  - kubernetes
  - rbac
  - openshift
  - multi-cluster
  - cluster
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: rbac-permissions-operator
        # Rules will be added here by the generate-csv.py script.
      deployments:
      - name: rbac-permissions-operator
        # Deployment spec will be added here by the generate-csv.py script.
  customresourcedefinitions:
    owned:
    - description: Reconcile SubjectPermissions to create ClusterRoleBinding and RoleBindings
      displayName: SubjectPermission
      kind: SubjectPermission
      name: subjectpermissions.managed.openshift.io
      version: v1alpha1